import type { PipelineStep, ExecutionContext, PipelineEvent, EventBus } from '@watchnt/pipeline';
import { createNoteId } from '@watchnt/shared';

export class FlashcardExtractionStep implements PipelineStep {
  name = 'FlashcardExtractionStep';
  context: ExecutionContext = 'worker';
  handles: PipelineEvent['type'][] = ['summary.ready'];

  async execute(event: PipelineEvent, bus: EventBus): Promise<void> {
    if (event.type !== 'summary.ready') return;
    const { contentId } = event.payload;

    await bus.publish({
      type: 'job.started',
      payload: { jobId: 'flashcard-' + contentId, stepName: this.name, contentId }
    });

    // Simulate progress
    await bus.publish({
      type: 'job.progress',
      payload: { jobId: 'flashcard-' + contentId, stepName: this.name, progress: 50 }
    });

    // Simulate latency for generating flashcards via LLM
    await new Promise(resolve => setTimeout(resolve, 100));

    const mockedFlashcards = [
      {
        question: `What is the main topic of ${contentId}?`,
        answer: 'This is a mock answer generated by the local pipeline.'
      },
      {
        question: 'What is a key concept mentioned in the video?',
        answer: 'Another mocked answer for demonstration.'
      }
    ];

    // Emit the flashcards.ready event
    await bus.publish({
      type: 'flashcards.ready',
      payload: {
        contentId,
        flashcards: mockedFlashcards
      }
    });

    await bus.publish({
      type: 'job.completed',
      payload: { jobId: 'flashcard-' + contentId, stepName: this.name, result: mockedFlashcards }
    });
  }
}
