import { Worker, type EventBus } from '@watchnt/pipeline';

export class FlashcardExtractionWorker extends Worker {
  constructor(bus: EventBus) {
    super('FlashcardExtraction', bus);
  }

  protected async process(contentId: string): Promise<void> {
    this.updateProgress(contentId, 0);
    
    // Simulate latency for generating flashcards via LLM
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    this.updateProgress(contentId, 50);

    const mockedFlashcards = [
      {
        question: `What is the main topic of ${contentId}?`,
        answer: 'This is a mock answer generated by the local pipeline.'
      },
      {
        question: 'What is a key concept mentioned in the video?',
        answer: 'Another mocked answer for demonstration.'
      }
    ];

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Emit the flashcards.ready event
    this.bus.publish({
      type: 'flashcards.ready',
      payload: {
        contentId,
        flashcards: mockedFlashcards
      },
      timestamp: Date.now(),
      source: this.name
    });

    this.updateProgress(contentId, 100);
  }
}
