from enum import Enum

class MeetingStatus(str, Enum):
    UPLOADING = "UPLOADING"
    TRANSCRIBING = "TRANSCRIBING"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    GENERATING_TITLE = "GENERATING_TITLE"
    EXTRACTING_INTELLIGENCE = "EXTRACTING_INTELLIGENCE"
    PERSISTING_MODEL = "PERSISTING_MODEL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
