from enum import Enum

class MeetingStatus(str, Enum):
    UPLOADING = "UPLOADING"
    TRANSCRIBING = "TRANSCRIBING"
    SUMMARIZING = "SUMMARIZING"
    EXTRACTING_ACTIONS = "EXTRACTING_ACTIONS"
    GENERATING_EMAIL = "GENERATING_EMAIL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
